### ISSUE TITLE
'custom' Verzeichnis

### ISSUE THREAD

**Issue by TB-archIT** [opsi4instituts/dfn_7zip#1]
bitte Feature einbauen https://opsi.wzb.eu/wiki/index.php/%27custom%27_Verzeichnis 

Zusätzlich wird eine Variable $InstallDirExe$ oder $PathToExe$ für das Anlegen einer Programmverknüpfung benötigt.

**Comment by iphtjena** [comment]
schau dir bitte die Version 0.66 an , ob es nun so passt

danke

**Comment by TB-archIT** [comment]
Nur damit niemand irritiert ist, das gehört zu dfn_putty.

**Comment by TB-archIT** [comment]
Ab "dfn_7zip_15.12-2.opsi" verfügbar
